[tool.commitizen]
name = "cz_conventional_commits"
version_scheme = "semver2"
tag_format = "$version"
update_changelog_on_bump = true
version = "3.0.0
bump_message = "chore(release): $current_version â†’ $new_version"