services:
  web:
    container_name: web_app_container
    env_file:
      - ../.env.docker.example
    expose:
      - "5000"
    depends_on:
      - db
      - selenium-hub
    build:
      context: ../
      dockerfile: docker/images/Dockerfile.dev
    volumes:
      - ../:/app
      - /var/run/docker.sock:/var/run/docker.sock
    command: [ "sh", "-c", "sh /app/docker/entrypoints/development_entrypoint.sh" ]
    networks:
      - uvlhub_network

  db:
    container_name: mariadb_container
    env_file:
      - ../.env.docker.example
    build:
      context: ../
      dockerfile: docker/images/Dockerfile.mariadb

    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: cerveza_hub
      MARIADB_USER: uvlhubdb_user
      MARIADB_PASSWORD: uvlhubdb_password

    restart: always
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - uvlhub_network

  nginx:
    container_name: nginx_web_server_container
    image: nginx:1.29.1
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - uvlhub_network

  selenium-hub:
    container_name: selenium_hub_container
    image: selenium/hub:latest
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - uvlhub_network

  selenium-chrome:
    container_name: selenium_chrome_container
    image: selenium/node-chrome:latest
    shm_size: 2gb
    ports:
      - "5900:5900"
    env_file:
      - ../.env.selenium
    depends_on:
      - selenium-hub
    networks:
      - uvlhub_network

  selenium-firefox:
    container_name: selenium_firefox_container
    image: selenium/node-firefox:latest
    shm_size: 2gb
    ports:
      - "5901:5900"
    env_file:
      - ../.env.selenium
    depends_on:
      - selenium-hub
    networks:
      - uvlhub_network

volumes:
  db_data:

networks:
  uvlhub_network:
