# ----------------------------------------------------------------------------
# Publish image in Docker Hub Workflow
# This workflow builds and pushes a Docker image to Docker Hub whenever
# a new release is published on GitHub.
# ----------------------------------------------------------------------------

name: Publish image in Docker Hub

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    runs-on: ubuntu-24.04

    steps:
      # 1. Checkout del repositorio
      - uses: actions/checkout@v5

      # 2. Login a Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build y push de la imagen
      - name: Build and push Docker image
        run: |
          TAG=${{ github.event.release.tag_name }}
          IMAGE=${{ secrets.DOCKER_USER }}/cerveza-hub

          echo "Publicando imagen con tag: $TAG"

          docker build --build-arg VERSION_TAG=$TAG -t $IMAGE:$TAG -f docker/images/Dockerfile.render .
          docker push $IMAGE:$TAG

          
          docker tag $IMAGE:$TAG $IMAGE:latest
          docker push $IMAGE:latest
