name: Deploy to Render Production

on:
  workflow_run:
    workflows:
      - Codacy CI
      - Pytest
      - Publish image in Docker Hub
    types:
      - completed

jobs:
  deploy:
    name: Deploy to Render
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Deploy to Render (Production)
        env:
          FERNET_KEY: ${{ secrets.FERNET_KEY }}
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL_PROD }}
        run: |
          curl "$deploy_url"