name: Tag

on:
  push:
    branches:
      - main

jobs:
  bump_version:
    if: "!startsWith(github.event.head_commit.message, 'chore(release):')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: "${{ secrets.ADMIN_TOKEN }}"

      - id: cz
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.ADMIN_TOKEN }}
          git_name: "Cristinafernandezchica"
          git_email: "correoparacristina100@gmail.com"

      - name: Print Version
        run: echo "Bumped to version ${{ steps.cz.outputs.version }}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.cz.outputs.version }}
          name: Release ${{ steps.cz.outputs.version }}
          body_path: CHANGELOG.md
          token: ${{ secrets.ADMIN_TOKEN }} 