name: Preproduction deploy

on:
  workflow_run:
    workflows:
      - Codacy CI
      - Python Lint
    types:
      - completed

jobs:
  deploy:
    name: Preproduction deploy
    
    if: >
      ${{ github.event.workflow_run.conclusion == 'success' &&
          github.event.workflow_run.head_branch == 'trunk' }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Deploy to Render
        env:
          FERNET_KEY: ${{ secrets.FERNET_KEY }}
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"